name: Setup

on: workflow_call

jobs:
  setup:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci
